server:
  port:  8083

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: micreservices
  application:
    name: Hotel_service
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8084/eureka}     